version: 1
services:
  - type: web
    name: milana-backend
    runtime: python
    plan: free
    envVars:
      - key: PORT
        value: 8000
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
