name: AKSI Autostart (every 5 minutes)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

concurrency:
  group: aksi-autostart
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Start FastAPI
        run: nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

      - name: Download cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start tunnel (limit 3m)
        id: tunnel
        run: |
          set -e
          cloudflared tunnel --url http://localhost:8000 --no-autoupdate > tunnel.log 2>&1 &
          # give tunnel time to start
          for i in $(seq 1 30); do
            URL=$(grep -o 'https://[a-zA-Z0-9.-]*trycloudflare.com' tunnel.log | head -n1 || true)
            if [ -n "$URL" ]; then break; fi;
            sleep 2;
          done
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Public URL: $URL"
          # hold ~2.5 minutes so runner stays up; total job limit 4 min
          sleep 150

      - name: Post URL as comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.tunnel.outputs.url }}' || '(not found)';
            const body = `🔓 AKSI backend live (5-min cron): ${url}`;
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner, repo: context.repo.repo,
              commit_sha: context.sha, body
            });
