name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          python -m pip install ruff
          ruff check .
      - name: Unit tests (pytest)
        run: |
          python -m pytest -q
      - name: Start server (smoke)
        run: |
          nohup uvicorn app.main:app --port 8000 &
          sleep 2
          curl -sSf http://127.0.0.1:8000/health
