name: Run AKSI backend via Cloudflare Tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    concurrency:
      group: aksi-backend
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Start FastAPI
        run: nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

      - name: Download cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start tunnel
        id: tunnel
        run: |
          set -e
          cloudflared tunnel --url http://localhost:8000 --no-autoupdate > tunnel.log 2>&1 &
          sleep 8
          URL=$(grep -o 'https://[a-zA-Z0-9.-]*trycloudflare.com' tunnel.log | head -n1 || true)
          test -n "$URL"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Public URL: $URL"

      - name: Save endpoint artifact
        run: |
          echo "{\"url\":\"${{ steps.tunnel.outputs.url }}\",\"updated\":\"$(date -u +%FT%TZ)\"}" > endpoint.json
          cat endpoint.json

      - name: Upload endpoint artifact
        uses: actions/upload-artifact@v4
        with:
          name: endpoint
          path: endpoint.json
